In [1]:
import numpy as np

In [2]:
data = np.load("ggt.npz")
X = data["X"]
y = data["y"]

In [11]:
np.unique(np.isnan(X).all(axis=2).astype(np.int32).sum(axis=-1), return_counts=True)

(array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
         13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
         26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
         39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
         52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  64,  65,
         66,  67,  68,  69,  71,  73,  74,  75,  78,  79,  83,  84,  88,
         90,  91,  99, 109, 112, 116, 121, 147]),
 array([ 1,  2,  3,  1,  1,  4,  5,  6,  6, 12,  4,  8, 11, 14,  9,  7,  6,
         7, 15,  7,  8,  9, 13, 11, 11,  8, 11,  5, 15, 11, 12,  8,  9, 12,
         4, 11,  9, 10,  5, 12,  6,  6,  3,  9,  4,  4,  4,  3,  5,  4,  1,
         5,  3,  7,  3,  4,  2,  4,  2,  1,  2,  3,  3,  1,  2,  4,  3,  2,
         1,  1,  2,  1,  2,  2,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         1], dtype=int64))

In [15]:
np.where(np.isnan(X).all(axis=2).astype(np.int32).sum(axis=-1)>69)

(array([ 65,  90, 112, 121, 131, 136, 195, 203, 208, 239, 254, 257, 260,
        264, 266, 278, 279, 290, 308, 379], dtype=int64),)